# plot_language_breakdown.gp — Language composition over Debian releases
# This script aggregates the top languages from tokei_summary.csv
reset

set terminal pdfcairo enhanced font "Helvetica,11" size 7in,4.5in
if (!exists("OUTDIR")) OUTDIR = '../../output/figures'
if (!exists("DATADIR")) DATADIR = '../../output/results'
set output OUTDIR.'/language_breakdown.pdf'

set datafile separator ","
set style data histogram
set style histogram rowstacked
set style fill solid 0.8 border -1
set boxwidth 0.7

set title "Programming Language Composition in Persistent Base Packages"
set xlabel "Release (Year)" offset 0,-1
set ylabel "Lines of Code (thousands)"

set xtics rotate by -38 
set grid ytics
set key outside right top

# This plot requires a pre-processed CSV: results/language_by_release.csv
# Format: codename,year,C,Shell,Assembly,Python,Perl,Other
# Generated by a helper step in the Makefile or manually.
#
# Python (column 6) is folded into "Other" (column 8) rather than drawn as its
# own band: it never exceeds ~0.4% of total LOC, so a dedicated slice and legend
# entry would be invisible in every bar and overstate a contribution the figure
# cannot actually render. Stack order: C, Shell, Assembly, Perl, Other (+Python).

plot DATADIR.'/language_by_release.csv' every ::1 \
    using ($3/1000.0):xtic(sprintf("%s\n(%s)", stringcolumn(1), stringcolumn(2))) title "C" lc rgb "#2E86C1", \
    '' every ::1 using ($4/1000.0) title "Shell" lc rgb "#27AE60", \
    '' every ::1 using ($5/1000.0) title "Assembly" lc rgb "#E74C3C", \
    '' every ::1 using ($7/1000.0) title "Perl" lc rgb "#8E44AD", \
    '' every ::1 using (($6+$8)/1000.0) title "Other" lc rgb "#95A5A6"
